2022-02-27 20:12:42,654 INFO: AutoArki startup [in C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\__init__.py:44]
2022-02-27 20:12:54,120 ERROR: Exception on /account_settings [GET] [in C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\routes.py", line 111, in account_settings
    form = EditAccountForm(current_user.email)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\forms.py", line 30, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
NameError: name 'EditProfileForm' is not defined
2022-02-27 20:14:22,366 ERROR: Exception on /account_settings [GET] [in C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\routes.py", line 111, in account_settings
    form = EditAccountForm(current_user.email)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\forms.py", line 30, in __init__
    super(EditAccountForm, self).__init__(*args, **kwargs)
NameError: name 'EditProfileForm' is not defined
2022-02-27 20:14:31,075 ERROR: Exception on /account_settings [GET] [in C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\routes.py", line 111, in account_settings
    form = EditAccountForm(current_user.email)
  File "C:\Users\embra\Documents\autoarki\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\forms.py", line 30, in __init__
    super(EditAccountForm, self).__init__(*args, **kwargs)
NameError: name 'EditProfileForm' is not defined
2022-02-27 20:14:46,676 INFO: AutoArki startup [in C:\Users\embra\Google Drive\Berkeley\capstone\archidoc_checker\autoarki_flask_app\app\__init__.py:44]
